name: Cargo Build & Test

on:
  push:

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        operating-system:
          - "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - run: cargo build --verbose
      - run: cargo test --verbose
  